### PR TITLE
Updated Google Collections Dependency (latest)

### PR DESCRIPTION
**Pull request by wcmatthysen**
Hi there,

This is the latest cleaner patch without all the indentation changes.

Commit:
-- Updated the pom so that atunit depends on a more recent release of
google collections (instead of the old snapshot). A couple of files
changes as a result of this due to the change in google-collections
API.

### CODE REVIEW

**Comment by gudmundur** [comment]
Thanks. I took a better look at this now tonight and noticed that google-collections has been deprecated in favor of google-guava (it's been a while since I've done any proper Java work). I'm a bit busy right now, so I can't really try it out with Guava. If you don't mind, could you try switching out the dependency and see if it works? Otherwise I can get to it in a few days time. Cheers!

**Comment by wcmatthysen** [comment]
Cool, I will try with Guava, and send you the updated patch.

**Comment by wcmatthysen** [comment]
Guava works nicely. All the tests still pass.

**Comment by gudmundur** [comment]
Thanks!

**Comment by gudmundur** [comment]
Oops, only noticed the distributionManagement section in pom.xml after I merged. Pulling that one out as we speak.

**Comment by wcmatthysen** [comment]
O yes, sorry. I forgot about that. Thanks

**Pull request merged**
